<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\Query\AST\Functions\IdentityFunction;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpFoundation\Request;


/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    private $em;

    public function __construct(EntityManager $em, Mapping\ClassMetadata $class)
    {
        $this->em = $em;
        parent::__construct($em, $class);
    }

    public function getMessages()
    {
        $dql = "SELECT m, u, m.id, m.body, m.createdAt, u.username FROM AppBundle:Message m JOIN m.User u";

        $query = $this->em->createQuery($dql)
                           ->setFirstResult(0)
                           ->setMaxResults(50);
        $result = $query->getScalarResult();



        $query1 = $this->em->createQueryBuilder()
                           ->select('a','a.file')
                           ->from('AppBundle:Attachment','a')
                           ->where('a.message = a.id')
                           ->setFirstResult(0)
                           ->setMaxResults(50);


        $paginator = new Paginator($query1, $fetchJoinCollections = true);

        $c = count($paginator);
        foreach ($paginator as $result)
        {
            $arr[] = $result;
        }


        dump($query1->getQuery()->getScalarResult());

    }


}
