<?php

namespace AppBundle\Repository;

/**
 * Chat_usersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userRepository extends \Doctrine\ORM\EntityRepository
{
}
