# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Chat_user: bcrypt


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        my_db_provider:
            entity:
                class: AppBundle:Chat_user
                property: username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            json_login:
                check_path: /login
            pattern: ^/
            http_basic: ~
            provider: my_db_provider
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
